export interface Country {
    fips: string;
    dial_code: string;
}

export const countries: Country[] = [
    {fips: 'dz', dial_code: '+213'},
    {fips: 'ao', dial_code: '+244'},
    {fips: 'bj', dial_code: '+229'},
    {fips: 'bw', dial_code: '+267'},
    {fips: 'bf', dial_code: '+226'},
    {fips: 'bi', dial_code: '+257'},
    {fips: 'cm', dial_code: '+237'},
    {fips: 'cv', dial_code: '+238'},
    {fips: 'cf', dial_code: '+236'},
    {fips: 'km', dial_code: '+269'},
    {fips: 'cd', dial_code: '+243'},
    {fips: 'dj', dial_code: '+253'},
    {fips: 'eg', dial_code: '+20'},
    {fips: 'gq', dial_code: '+240'},
    {fips: 'er', dial_code: '+291'},
    {fips: 'et', dial_code: '+251'},
    {fips: 'ga', dial_code: '+241'},
    {fips: 'gm', dial_code: '+220'},
    {fips: 'gh', dial_code: '+233'},
    {fips: 'gn', dial_code: '+224'},
    {fips: 'gw', dial_code: '+245'},
    {fips: 'ci', dial_code: '+225'},
    {fips: 'ke', dial_code: '+254'},
    {fips: 'ls', dial_code: '+266'},
    {fips: 'lr', dial_code: '+231'},
    {fips: 'ly', dial_code: '+218'},
    {fips: 'mg', dial_code: '+261'},
    {fips: 'mw', dial_code: '+265'},
    {fips: 'ml', dial_code: '+223'},
    {fips: 'mr', dial_code: '+222'},
    {fips: 'mu', dial_code: '+230'},
    {fips: 'ma', dial_code: '+212'},
    {fips: 'mz', dial_code: '+258'},
    {fips: 'na', dial_code: '+264'},
    {fips: 'ne', dial_code: '+227'},
    {fips: 'ng', dial_code: '+234'},
    {fips: 'cg', dial_code: '+242'},
    {fips: 're', dial_code: '+262'},
    {fips: 'rw', dial_code: '+250'},
    {fips: 'sh', dial_code: '+290'},
    {fips: 'st', dial_code: '+239'},
    {fips: 'sn', dial_code: '+221'},
    {fips: 'sc', dial_code: '+248'},
    {fips: 'sl', dial_code: '+232'},
    {fips: 'so', dial_code: '+252'},
    {fips: 'za', dial_code: '+27'},
    {fips: 'ss', dial_code: '+211'},
    {fips: 'sd', dial_code: '+249'},
    {fips: 'sz', dial_code: '+268'},
    {fips: 'tz', dial_code: '+255'},
    {fips: 'tg', dial_code: '+228'},
    {fips: 'tn', dial_code: '+216'},
    {fips: 'ug', dial_code: '+256'},
    {fips: 'eh', dial_code: '+212'},
    {fips: 'zm', dial_code: '+260'},
    {fips: 'zw', dial_code: '+263'},
];
